# Generated by Django 3.2.25 on 2024-12-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.CharField(choices=[('工科数学分析（上）', '工科数学分析（上）'), ('工科数学分析（下）', '工科数学分析（下）'), ('工科高等代数', '工科高等代数'), ('离散数学（信息类）', '离散数学（信息类）'), ('基础物理学A', '基础物理学A')], default='工科数学分析（上）', max_length=100),
        ),
        migrations.AddField(
            model_name='examrecord',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
