# Generated by Django 3.2.25 on 2024-11-26 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='release_time',
            new_name='releaseTime',
        ),
    ]
