# Generated by Django 3.2.25 on 2024-12-11 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_blacklist'),
        ('broadcast', '0002_broadcast_last_updated_broadcast_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_broadcasts', to='users.user'),
        ),
    ]
