# Generated by Django 3.2.25 on 2024-12-11 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_blacklist'),
        ('broadcast', '0003_alter_broadcast_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='sender_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='users.user'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='sender',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
