# Generated by Django 5.1.1 on 2024-11-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questiondiscussion_questioncomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('工科数学分析（上）', '工科数学分析（上）'), ('工科数学分析（下）', '工科数学分析（下）'), ('工科高等代数', '工科高等代数'), ('离散数学（信息类）', '离散数学（信息类）'), ('基础物理学A', '基础物理学A')], max_length=100),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='subject',
            field=models.CharField(choices=[('工科数学分析（上）', '工科数学分析（上）'), ('工科数学分析（下）', '工科数学分析（下）'), ('工科高等代数', '工科高等代数'), ('离散数学（信息类）', '离散数学（信息类）'), ('基础物理学A', '基础物理学A')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userquestionrecord',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
