# Generated by Django 3.2.25 on 2024-12-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_remove_question_question_banks'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
