# Generated by Django 5.1.1 on 2024-11-22 14:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_blacklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('avatar', models.URLField(blank=True, null=True)),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(blank=True, choices=[('工科数学分析（上）', '工科数学分析（上）'), ('工科数学分析（下）', '工科数学分析（下）'), ('工科高等代数', '工科高等代数'), ('离散数学（信息类）', '离散数学（信息类）'), ('基础物理学A', '基础物理学A')], max_length=100, null=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_discussions', to='users.user')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_discussions', to='users.user')),
                ('subscribers', models.ManyToManyField(blank=True, related_name='subscribed_discussions', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('avatar', models.URLField(blank=True, null=True)),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='discussions.discussion')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_replies', to='users.user')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_replies', to='users.user')),
            ],
        ),
    ]
