# Generated by Django 5.1.1 on 2024-11-21 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('users', '0003_blacklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDiscussion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_discussions', to='users.user')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='questions.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creator_avatar', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_comments', to='users.user')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_comments', to='users.user')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='questions.questiondiscussion')),
            ],
        ),
    ]
