# Generated by Django 5.1.1 on 2024-11-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_userquestionrecord_question_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('单项选择题', '单项选择题'), ('多项选择题', '多项选择题'), ('判断题', '判断题'), ('填空题', '填空题'), ('问答题', '问答题')], max_length=20),
        ),
    ]
