# Generated by Django 3.2.25 on 2024-11-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0002_auto_20241121_2338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
